module.exports = [
  { number: 1, question: "Quelle est la capitale du Canada ?", choices: ["Ottawa", "Toronto", "Montréal"], correctAnswer: "Ottawa" },
  { number: 2, question: "Combien font 14 x 3 ?", choices: ["42", "44", "48"], correctAnswer: "42" },
  { number: 3, question: "Quel animal glousse ?", choices: ["Poule", "Canard", "Dinde"], correctAnswer: "Poule" },
  { number: 4, question: "Quelle planète est la plus grande du système solaire ?", choices: ["Jupiter", "Saturne", "Terre"], correctAnswer: "Jupiter" },
  { number: 5, question: "Combien de mois comportent 31 jours ?", choices: ["5", "6", "7"], correctAnswer: "7" },
  { number: 6, question: "Quelle est la capitale de l’Australie ?", choices: ["Sydney", "Canberra", "Melbourne"], correctAnswer: "Canberra" },
  { number: 7, question: "Quel animal est célèbre pour sa mémoire ?", choices: ["Éléphant", "Chat", "Renard"], correctAnswer: "Éléphant" },
  { number: 8, question: "Combien font 81 ÷ 9 ?", choices: ["8", "9", "10"], correctAnswer: "9" },
  { number: 9, question: "Quel organe sert à respirer ?", choices: ["Poumons", "Foie", "Cerveau"], correctAnswer: "Poumons" },
  { number: 10, question: "Quel est le plus long fleuve du monde ?", choices: ["Nil", "Amazonie", "Yangtsé"], correctAnswer: "Nil" },
  { number: 11, question: "Combien de côtés possède un pentagone ?", choices: ["4", "5", "6"], correctAnswer: "5" },
  { number: 12, question: "Quel animal porte ses petits dans une poche ?", choices: ["Kangourou", "Cheval", "Loup"], correctAnswer: "Kangourou" },
  { number: 13, question: "Quelle couleur obtient-on avec bleu + rouge ?", choices: ["Violet", "Orange", "Vert"], correctAnswer: "Violet" },
  { number: 14, question: "Combien font 17 + 26 ?", choices: ["41", "42", "43"], correctAnswer: "43" },
  { number: 15, question: "Quelle est la langue officielle de l’Argentine ?", choices: ["Espagnol", "Portugais", "Anglais"], correctAnswer: "Espagnol" },
  { number: 16, question: "Quel objet sert à mesurer le temps ?", choices: ["Horloge", "Balance", "Compas"], correctAnswer: "Horloge" },
  { number: 17, question: "Quel animal vit principalement dans les océans ?", choices: ["Dauphin", "Renard", "Girafe"], correctAnswer: "Dauphin" },
  { number: 18, question: "Combien font 144 ÷ 12 ?", choices: ["10", "11", "12"], correctAnswer: "12" },
  { number: 19, question: "Quelle saison suit le printemps ?", choices: ["Été", "Automne", "Hiver"], correctAnswer: "Été" },
  { number: 20, question: "Quel métal précieux est jaune ?", choices: ["Or", "Argent", "Cuivre"], correctAnswer: "Or" },
];