module.exports = [
  {
    number: 1,
    question: "Quel océan borde la côte ouest de la France ?",
    choices: ["Pacifique", "Atlantique", "Indien"],
    correctAnswer: "Atlantique",
  },
  {
    number: 2,
    question: "Combien font 8 x 7 ?",
    choices: ["54", "56", "64"],
    correctAnswer: "56",
  },
  {
    number: 3,
    question: "Quelle planète est la plus proche du Soleil ?",
    choices: ["Mars", "Mercure", "Vénus"],
    correctAnswer: "Mercure",
  },
  {
    number: 4,
    question: "Quel animal est surnommé le roi de la jungle ?",
    choices: ["Tigre", "Lion", "Éléphant"],
    correctAnswer: "Lion",
  },
  {
    number: 5,
    question: "Combien de continents existe-t-il ?",
    choices: ["5", "6", "7"],
    correctAnswer: "7",
  },
  {
    number: 6,
    question: "Quelle est la capitale de l’Espagne ?",
    choices: ["Madrid", "Barcelone", "Lisbonne"],
    correctAnswer: "Madrid",
  },
  {
    number: 7,
    question: "Quel gaz respirons-nous principalement ?",
    choices: ["Azote", "Oxygène", "Hydrogène"],
    correctAnswer: "Oxygène",
  },
  {
    number: 8,
    question: "Combien font 15 + 27 ?",
    choices: ["42", "41", "43"],
    correctAnswer: "42",
  },
  {
    number: 9,
    question: "Quel est le plus grand mammifère marin ?",
    choices: ["Requin", "Baleine bleue", "Dauphin"],
    correctAnswer: "Baleine bleue",
  },
  {
    number: 10,
    question: "Quelle couleur obtient-on avec rouge + jaune ?",
    choices: ["Vert", "Orange", "Bleu"],
    correctAnswer: "Orange",
  },
  {
    number: 11,
    question: "Quel pays a la forme d’une botte ?",
    choices: ["Portugal", "Italie", "Grèce"],
    correctAnswer: "Italie",
  },
  {
    number: 12,
    question: "Combien de côtés possède un hexagone ?",
    choices: ["5", "6", "8"],
    correctAnswer: "6",
  },
  {
    number: 13,
    question: "Quel instrument mesure la température ?",
    choices: ["Thermomètre", "Baromètre", "Télescope"],
    correctAnswer: "Thermomètre",
  },
  {
    number: 14,
    question: "Combien font 9² ?",
    choices: ["81", "72", "99"],
    correctAnswer: "81",
  },
  {
    number: 15,
    question: "Quel est le symbole chimique de l’eau ?",
    choices: ["CO2", "H2O", "O2"],
    correctAnswer: "H2O",
  },
  {
    number: 16,
    question: "Quel animal pond des œufs ?",
    choices: ["Poule", "Chat", "Chien"],
    correctAnswer: "Poule",
  },
  {
    number: 17,
    question: "Quelle est la monnaie du Japon ?",
    choices: ["Won", "Yuan", "Yen"],
    correctAnswer: "Yen",
  },
  {
    number: 18,
    question: "Quel est le plus grand désert du monde ?",
    choices: ["Sahara", "Arctique", "Gobi"],
    correctAnswer: "Sahara",
  },
  {
    number: 19,
    question: "Combien font 100 ÷ 4 ?",
    choices: ["20", "25", "30"],
    correctAnswer: "25",
  },
  {
    number: 20,
    question: "Quel métal est attiré par un aimant ?",
    choices: ["Fer", "Or", "Aluminium"],
    correctAnswer: "Fer",
  },
];