module.exports = [
  { number: 1, question: "Quelle est la capitale du Japon ?", choices: ["Tokyo", "Osaka", "Kyoto"], correctAnswer: "Tokyo" },
  { number: 2, question: "Combien font 25 x 4 ?", choices: ["90", "100", "110"], correctAnswer: "100" },
  { number: 3, question: "Quel animal coasse ?", choices: ["Grenouille", "Poisson", "Pigeon"], correctAnswer: "Grenouille" },
  { number: 4, question: "Quelle planète est connue pour ses températures très élevées ?", choices: ["Vénus", "Mars", "Neptune"], correctAnswer: "Vénus" },
  { number: 5, question: "Combien de jours y a-t-il dans une année normale ?", choices: ["364", "365", "366"], correctAnswer: "365" },
  { number: 6, question: "Quelle est la capitale du Maroc ?", choices: ["Casablanca", "Rabat", "Marrakech"], correctAnswer: "Rabat" },
  { number: 7, question: "Quel animal produit de la laine ?", choices: ["Mouton", "Chèvre", "Cheval"], correctAnswer: "Mouton" },
  { number: 8, question: "Combien font 49 + 51 ?", choices: ["90", "100", "110"], correctAnswer: "100" },
  { number: 9, question: "Quel organe sert à penser ?", choices: ["Cerveau", "Cœur", "Foie"], correctAnswer: "Cerveau" },
  { number: 10, question: "Quel est le plus grand océan ?", choices: ["Pacifique", "Atlantique", "Indien"], correctAnswer: "Pacifique" },
  { number: 11, question: "Combien de côtés possède un octogone ?", choices: ["6", "7", "8"], correctAnswer: "8" },
  { number: 12, question: "Quel animal est le plus grand terrestre ?", choices: ["Éléphant", "Girafe", "Rhinocéros"], correctAnswer: "Éléphant" },
  { number: 13, question: "Quelle couleur obtient-on avec jaune + rouge ?", choices: ["Orange", "Vert", "Violet"], correctAnswer: "Orange" },
  { number: 14, question: "Combien font 18 x 2 ?", choices: ["34", "36", "38"], correctAnswer: "36" },
  { number: 15, question: "Quelle est la monnaie des États-Unis ?", choices: ["Dollar", "Euro", "Peso"], correctAnswer: "Dollar" },
  { number: 16, question: "Quel objet sert à couper du papier ?", choices: ["Ciseaux", "Marteau", "Clé"], correctAnswer: "Ciseaux" },
  { number: 17, question: "Quel animal vit dans les régions polaires ?", choices: ["Ours polaire", "Lion", "Tigre"], correctAnswer: "Ours polaire" },
  { number: 18, question: "Combien font 200 ÷ 5 ?", choices: ["20", "30", "40"], correctAnswer: "40" },
  { number: 19, question: "Quelle saison précède l’été ?", choices: ["Printemps", "Automne", "Hiver"], correctAnswer: "Printemps" },
  { number: 20, question: "Quel gaz est indispensable au feu ?", choices: ["Oxygène", "Azote", "Hélium"], correctAnswer: "Oxygène" },
];