module.exports = [
  { number: 1, question: "Quelle est la capitale de la Chine ?", choices: ["Pékin", "Shanghai", "Hong Kong"], correctAnswer: "Pékin" },
  { number: 2, question: "Combien font 16 x 5 ?", choices: ["70", "80", "90"], correctAnswer: "80" },
  { number: 3, question: "Quel animal est surnommé le meilleur ami de l’homme ?", choices: ["Chien", "Chat", "Cheval"], correctAnswer: "Chien" },
  { number: 4, question: "Quelle planète est appelée la planète rouge ?", choices: ["Mars", "Mercure", "Saturne"], correctAnswer: "Mars" },
  { number: 5, question: "Combien y a-t-il d’heures dans une journée ?", choices: ["12", "24", "36"], correctAnswer: "24" },
  { number: 6, question: "Quelle est la capitale de la Grèce ?", choices: ["Athènes", "Sparte", "Rome"], correctAnswer: "Athènes" },
  { number: 7, question: "Quel animal vit dans l’eau et possède des branchies ?", choices: ["Poisson", "Lapin", "Cheval"], correctAnswer: "Poisson" },
  { number: 8, question: "Combien font 121 ÷ 11 ?", choices: ["10", "11", "12"], correctAnswer: "11" },
  { number: 9, question: "Quel organe permet de digérer ?", choices: ["Estomac", "Poumons", "Cerveau"], correctAnswer: "Estomac" },
  { number: 10, question: "Quel est le plus haut sommet du monde ?", choices: ["Everest", "Mont Blanc", "K2"], correctAnswer: "Everest" },
  { number: 11, question: "Combien de côtés possède un cercle ?", choices: ["0", "1", "2"], correctAnswer: "0" },
  { number: 12, question: "Quel animal est connu pour changer de couleur ?", choices: ["Caméléon", "Serpent", "Chat"], correctAnswer: "Caméléon" },
  { number: 13, question: "Quelle couleur obtient-on avec rouge + bleu + jaune ?", choices: ["Marron", "Vert", "Rose"], correctAnswer: "Marron" },
  { number: 14, question: "Combien font 50 + 75 ?", choices: ["115", "120", "125"], correctAnswer: "125" },
  { number: 15, question: "Quelle est la monnaie du Royaume-Uni ?", choices: ["Livre sterling", "Euro", "Dollar"], correctAnswer: "Livre sterling" },
  { number: 16, question: "Quel objet sert à écrire au tableau ?", choices: ["Craie", "Fourchette", "Tournevis"], correctAnswer: "Craie" },
  { number: 17, question: "Quel animal est célèbre pour ses bosses ?", choices: ["Chameau", "Cheval", "Vache"], correctAnswer: "Chameau" },
  { number: 18, question: "Combien font 150 ÷ 3 ?", choices: ["40", "50", "60"], correctAnswer: "50" },
  { number: 19, question: "Quelle saison suit l’automne ?", choices: ["Hiver", "Printemps", "Été"], correctAnswer: "Hiver" },
  { number: 20, question: "Quel métal est liquide à température ambiante ?", choices: ["Mercure", "Fer", "Aluminium"], correctAnswer: "Mercure" },
];