module.exports = [
  { number: 1, question: "Quelle est la capitale des États-Unis ?", choices: ["Washington", "New York", "Los Angeles"], correctAnswer: "Washington" },
  { number: 2, question: "Combien font 9 x 5 ?", choices: ["40", "45", "50"], correctAnswer: "45" },
  { number: 3, question: "Quel animal rugit ?", choices: ["Lion", "Vache", "Canard"], correctAnswer: "Lion" },
  { number: 4, question: "Quelle planète est surnommée la planète bleue ?", choices: ["Terre", "Mars", "Neptune"], correctAnswer: "Terre" },
  { number: 5, question: "Combien y a-t-il de secondes dans une minute ?", choices: ["30", "60", "90"], correctAnswer: "60" },
  { number: 6, question: "Quelle est la capitale de la Suisse ?", choices: ["Berne", "Genève", "Zurich"], correctAnswer: "Berne" },
  { number: 7, question: "Quel animal cancane ?", choices: ["Canard", "Chat", "Chèvre"], correctAnswer: "Canard" },
  { number: 8, question: "Combien font 100 - 37 ?", choices: ["63", "67", "73"], correctAnswer: "63" },
  { number: 9, question: "Quel organe pompe le sang ?", choices: ["Cœur", "Foie", "Estomac"], correctAnswer: "Cœur" },
  { number: 10, question: "Quel est le plus petit continent ?", choices: ["Océanie", "Europe", "Afrique"], correctAnswer: "Océanie" },
  { number: 11, question: "Combien de côtés possède un carré ?", choices: ["3", "4", "5"], correctAnswer: "4" },
  { number: 12, question: "Quel animal possède une trompe ?", choices: ["Éléphant", "Girafe", "Rhinocéros"], correctAnswer: "Éléphant" },
  { number: 13, question: "Quelle couleur obtient-on avec rouge + blanc ?", choices: ["Rose", "Orange", "Violet"], correctAnswer: "Rose" },
  { number: 14, question: "Combien font 13 + 29 ?", choices: ["40", "42", "44"], correctAnswer: "42" },
  { number: 15, question: "Quelle est la langue officielle du Brésil ?", choices: ["Portugais", "Espagnol", "Français"], correctAnswer: "Portugais" },
  { number: 16, question: "Quel objet sert à peser ?", choices: ["Balance", "Règle", "Boussole"], correctAnswer: "Balance" },
  { number: 17, question: "Quel animal est connu pour ses rayures ?", choices: ["Zèbre", "Lion", "Ours"], correctAnswer: "Zèbre" },
  { number: 18, question: "Combien font 72 ÷ 9 ?", choices: ["6", "8", "10"], correctAnswer: "8" },
  { number: 19, question: "Quelle saison vient avant l’hiver ?", choices: ["Automne", "Printemps", "Été"], correctAnswer: "Automne" },
  { number: 20, question: "Quel élément chimique a pour symbole O ?", choices: ["Oxygène", "Or", "Osmium"], correctAnswer: "Oxygène" },
];