module.exports = [
  { number: 1, question: "Quelle est la capitale de l’Allemagne ?", choices: ["Berlin", "Munich", "Vienne"], correctAnswer: "Berlin" },
  { number: 2, question: "Combien font 12 x 4 ?", choices: ["36", "48", "52"], correctAnswer: "48" },
  { number: 3, question: "Quel animal bêle ?", choices: ["La chèvre", "Le chien", "Le cheval"], correctAnswer: "La chèvre" },
  { number: 4, question: "Quelle planète possède des anneaux visibles ?", choices: ["Saturne", "Mars", "Mercure"], correctAnswer: "Saturne" },
  { number: 5, question: "Combien y a-t-il de minutes dans une heure ?", choices: ["50", "60", "100"], correctAnswer: "60" },
  { number: 6, question: "Quel est le contraire de rapide ?", choices: ["Lent", "Fort", "Court"], correctAnswer: "Lent" },
  { number: 7, question: "Quel fruit est souvent rouge ou vert ?", choices: ["Pomme", "Banane", "Orange"], correctAnswer: "Pomme" },
  { number: 8, question: "Combien font 45 - 18 ?", choices: ["27", "28", "29"], correctAnswer: "27" },
  { number: 9, question: "Quel organe permet de voir ?", choices: ["Les yeux", "Les oreilles", "Le nez"], correctAnswer: "Les yeux" },
  { number: 10, question: "Quelle est la capitale de l’Italie ?", choices: ["Rome", "Milan", "Naples"], correctAnswer: "Rome" },
  { number: 11, question: "Combien de joueurs compte une équipe de football sur le terrain ?", choices: ["9", "10", "11"], correctAnswer: "11" },
  { number: 12, question: "Quel animal est connu pour sa lenteur ?", choices: ["Escargot", "Guépard", "Aigle"], correctAnswer: "Escargot" },
  { number: 13, question: "Quelle couleur obtient-on avec rouge + bleu ?", choices: ["Violet", "Vert", "Orange"], correctAnswer: "Violet" },
  { number: 14, question: "Combien font 6 x 6 ?", choices: ["30", "36", "42"], correctAnswer: "36" },
  { number: 15, question: "Quel pays a pour capitale Londres ?", choices: ["Royaume-Uni", "Irlande", "Canada"], correctAnswer: "Royaume-Uni" },
  { number: 16, question: "Quel objet indique le nord ?", choices: ["Boussole", "Montre", "Balance"], correctAnswer: "Boussole" },
  { number: 17, question: "Quel animal vit dans une ruche ?", choices: ["Abeille", "Fourmi", "Papillon"], correctAnswer: "Abeille" },
  { number: 18, question: "Combien font 90 ÷ 9 ?", choices: ["9", "10", "11"], correctAnswer: "10" },
  { number: 19, question: "Quelle saison vient après l’hiver ?", choices: ["Printemps", "Été", "Automne"], correctAnswer: "Printemps" },
  { number: 20, question: "Quel liquide est indispensable à la vie ?", choices: ["Eau", "Huile", "Essence"], correctAnswer: "Eau" },
];