module.exports = [
  { number: 1, question: "Quelle est la capitale du Portugal ?", choices: ["Lisbonne", "Porto", "Madrid"], correctAnswer: "Lisbonne" },
  { number: 2, question: "Combien font 7 x 8 ?", choices: ["54", "56", "64"], correctAnswer: "56" },
  { number: 3, question: "Quel animal hennit ?", choices: ["Cheval", "Chien", "Chat"], correctAnswer: "Cheval" },
  { number: 4, question: "Quel est le satellite naturel de la Terre ?", choices: ["La Lune", "Mars", "Le Soleil"], correctAnswer: "La Lune" },
  { number: 5, question: "Combien y a-t-il de voyelles dans l’alphabet français ?", choices: ["5", "6", "7"], correctAnswer: "6" },
  { number: 6, question: "Quelle est la capitale de la Belgique ?", choices: ["Bruxelles", "Liège", "Anvers"], correctAnswer: "Bruxelles" },
  { number: 7, question: "Quel animal porte une carapace ?", choices: ["Tortue", "Lapin", "Mouton"], correctAnswer: "Tortue" },
  { number: 8, question: "Combien font 33 + 44 ?", choices: ["77", "78", "87"], correctAnswer: "77" },
  { number: 9, question: "Quel organe permet d’entendre ?", choices: ["Oreilles", "Yeux", "Poumons"], correctAnswer: "Oreilles" },
  { number: 10, question: "Quel est le plus grand pays du monde ?", choices: ["Russie", "Canada", "Chine"], correctAnswer: "Russie" },
  { number: 11, question: "Combien de côtés possède un triangle ?", choices: ["3", "4", "5"], correctAnswer: "3" },
  { number: 12, question: "Quel animal est noir et blanc et mange du bambou ?", choices: ["Panda", "Zèbre", "Pingouin"], correctAnswer: "Panda" },
  { number: 13, question: "Quelle couleur obtient-on avec bleu + jaune ?", choices: ["Vert", "Rouge", "Rose"], correctAnswer: "Vert" },
  { number: 14, question: "Combien font 11 x 11 ?", choices: ["111", "121", "131"], correctAnswer: "121" },
  { number: 15, question: "Quelle est la monnaie utilisée en France ?", choices: ["Euro", "Franc", "Dollar"], correctAnswer: "Euro" },
  { number: 16, question: "Quel instrument sert à observer les étoiles ?", choices: ["Télescope", "Microscope", "Thermomètre"], correctAnswer: "Télescope" },
  { number: 17, question: "Quel animal est le plus rapide sur terre ?", choices: ["Guépard", "Lion", "Cheval"], correctAnswer: "Guépard" },
  { number: 18, question: "Combien font 64 ÷ 8 ?", choices: ["6", "8", "9"], correctAnswer: "8" },
  { number: 19, question: "Quelle saison est la plus chaude en France ?", choices: ["Été", "Hiver", "Automne"], correctAnswer: "Été" },
  { number: 20, question: "Quel gaz les plantes absorbent-elles principalement ?", choices: ["CO2", "Oxygène", "Azote"], correctAnswer: "CO2" },
];